# Generated by Django 6.0.3 on 2026-05-09 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('db_type', models.CharField(choices=[('sqlite', 'SQLite'), ('postgres', 'PostgreSQL')], max_length=20)),
                ('database', models.CharField(max_length=255)),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('ssl_mode', models.CharField(blank=True, default='prefer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MigrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('old_table', models.CharField(max_length=120)),
                ('new_table', models.CharField(max_length=120)),
                ('column_mapping', models.JSONField(default=dict)),
                ('batch_size', models.IntegerField(default=500)),
                ('stop_on_error', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PLANNING', 'PLANNING'), ('PROFILING', 'PROFILING'), ('MAPPING', 'MAPPING'), ('TRANSFORMING', 'TRANSFORMING'), ('LOADING', 'LOADING'), ('VERIFYING', 'VERIFYING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('stage', models.CharField(blank=True, default='', max_length=30)),
                ('rows_read', models.IntegerField(default=0)),
                ('rows_written', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_jobs', to='migration_engine.connectionprofile')),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_jobs', to='migration_engine.connectionprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MigrationRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='migration_engine.migrationjob')),
            ],
        ),
    ]
